This are the things I think we should cover

* What are we using (Jupyter Notebooks)
Jupyter notebooks can do all sort of cool things. They can be used for
displaying images, drawing vectorial images, linking videos, and
writing math equations.

* Basic Math
Introduction to numpy. 

* More complex math
A couple of tutorials of sympy.

* Opening files 
Wheter people have .csv, SQL databases, .hdf5 or images python can
handle that.

* Plotting complex things (matplotlib)
Matplotlib, compared to other systems like R, excel or Matlab produces
significantly prettier graphs, examples 
- plotting scatter plots depending on category straight out of a table
- plotting data over geographic maps
- an example of image processing (eg. sobel filter over the picture of
  a cat)

* Handling tables (pandas)
pandas Dataframes are a very potent implementation of the entity
relationship model.
- usefull for looking at data
- usefull for formatting latex tables
- one can look at time series (among other things)
